#import "RLSBasicModel.h"
@interface RLSQingBaoFPTwoModel : RLSBasicModel
@property (nonatomic, assign)NSInteger sid;
@property (nonatomic, retain)NSString *league;
@property (nonatomic, assign)NSInteger leagueId;
@property (nonatomic, retain)NSString *mtime;
@property (nonatomic, assign)NSInteger matchstate;
@property (nonatomic, retain)NSString *guestteam; 
@property (nonatomic, assign)NSInteger guestteamid;
@property (nonatomic, retain)NSString *hometeam;
@property (nonatomic, assign)NSInteger hometeamid;
@property (nonatomic, retain)NSString *homescore;
@property (nonatomic, retain)NSString *guestscore;
@property (nonatomic, assign)NSInteger newsid;
@property (nonatomic, assign)NSInteger choice;
@property (nonatomic, retain)NSString *tag;
@property (nonatomic, retain)NSString *title;
@property (nonatomic, retain)NSString *content;
@property (nonatomic, retain)NSString *upodds;
@property (nonatomic, retain)NSString *goals;
@property (nonatomic, retain)NSString *downodds;
@property (nonatomic, assign)NSInteger infoCount;
@property (nonatomic, assign)BOOL yOn;
@property (nonatomic, retain)NSString *sort;
@property (nonatomic, retain)NSString *leagueColor;
@property (nonatomic, retain)NSString *color;
@property (nonatomic, retain)NSString *createtime;
@property (nonatomic, retain)NSString *weekDayName;
@property (nonatomic, assign)NSInteger mark;
@end
